In [1]:
# numpy review

import numpy as np
import torch

In [18]:
# 1D Array with Numpy

# numpy 를 선언하기 
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print('t : ',t)

print('몇개의 차원으로 이루어졌나? : ', t.ndim)
print('Shape  : ', t.shape)
print()
print('t[0], t[1], t[-1] = ', t[0], t[1], t[-1])  # Element
print('t[2:5] t[4:-1]    = ', t[2:5], t[4:-1])    # Slicing
print('t[:2] t[3:]       = ', t[:2], t[3:])       # # Slicing

t :  [0. 1. 2. 3. 4. 5. 6.]
몇개의 차원으로 이루어졌나? :  1
Shape  :  (7,)

t[0], t[1], t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]    =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]       =  [0. 1.] [3. 4. 5. 6.]


In [13]:
# 2D Array with Numpy

t= np.array([[1,2,3], [4,5,6],[7,8,9], [10,11,12]])
print('t : ','\n', t)
print()
print('몇개의 차원으로 이루어졌나? : ', t.ndim)
print('Shape  : ', t.shape)
print()

t :  
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

몇개의 차원으로 이루어졌나? :  2
Shape  :  (4, 3)



### 1D Array with PyTorch

In [17]:
# torch 를 선언하기 
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print('t : ',t)

print('몇개의 차원으로 이루어졌나? : ', t.dim())  # rank
print('Shape  : ', t.shape)
print('Shape  : ', t.size())
print()
print('t[0], t[1], t[-1] = ', t[0], t[1], t[-1])  # Element
print('t[2:5] t[4:-1]    = ', t[2:5], t[4:-1])    # Slicing
print('t[:2] t[3:]       = ', t[:2], t[3:])       # # Slicing

t :  tensor([0., 1., 2., 3., 4., 5., 6.])
몇개의 차원으로 이루어졌나? :  1
Shape  :  torch.Size([7])
Shape  :  torch.Size([7])

t[0], t[1], t[-1] =  tensor(0.) tensor(1.) tensor(6.)
t[2:5] t[4:-1]    =  tensor([2., 3., 4.]) tensor([4., 5.])
t[:2] t[3:]       =  tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with Numpy


In [20]:
t= torch.FloatTensor([[1,2,3], [4,5,6],[7,8,9], [10,11,12]])
print('t : ','\n', t)
print()
print('몇개의 차원으로 이루어졌나? : ', t.dim())
print('Shape  : ', t.shape)
print('Shape  : ', t.size())
print()
print(t[:,1])  # 첫번째 차원은 다 가져오고, 두번째꺼에서는 1 번째만 가져오기
print(t[:,1].size())  # 벡터 
print(t[:, :-1])

t :  
 tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])

몇개의 차원으로 이루어졌나? :  2
Shape  :  torch.Size([4, 3])
Shape  :  torch.Size([4, 3])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### Broadcasting

- pytorch에는 Broadcasting기능을 제공한다.
- 자동적으로 사이즈를 맞춰서 연산을 수행한다.
- Broadcasting 는 자동적으로 실행되기 때문에, 사용자 입장에서 조심스럽게 사용해야한다. 

In [25]:
# same shape
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])

print(m1 + m2)
print()

# vector + scalar
# 원래는 크기가 안맞아서 연산이 안되지만, 자동으로 사이즈를 맞춰줌 
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3]])  # 3 - > [[3,3]]

print(m1 + m2)  # [[1,2]] + [[3,3]] = [[4, 5]]
print()

# 2 x 1 vector +  1 x 2 vector
# 텐서간의 연산에도 자동으로 1이 들어있는 차원을 늘려주어서 적용됨
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3],[4]])  

print(m1 + m2)
# [[1,2],[1,2]] + [[3,3],[4,4]] = [ [4,5],[5,6]]

tensor([[5., 5.]])

tensor([[4., 5.]])

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication ( 곱셈  vs 행렬 곱셈 )

In [35]:
print('일반적인 곱셈')
print('--------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1 :', m1.shape)  # 2 x 2
print('Shape of Matrix 1 :', m2.shape)  # 2 x 1 -> 브로드 캐스팅 2 X 2 됨
print('mul : ','\n',m1 * m2)            # 2 x 2

# [[1,2],[3,4]] X [[1,1], [2,2]]= [[1,2],[6,8]]
print()
print(m1.mul(m2))

print()
print('행렬 곱셈')
print('--------------')
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([[1],[2]])

print('Shape of Matrix 1 :', m1.shape)  # 2 x 2
print('Shape of Matrix 1 :', m2.shape)  # 2 x 1
# 행렬곱은 뒤의 차원과 앞의 차원의 크기가 같으면 됨 
print('mul : ','\n',m1.matmul(m2))      # 2 x 1



일반적인 곱셈
--------------
Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 1 : torch.Size([2, 1])
mul :  
 tensor([[1., 2.],
        [6., 8.]])

tensor([[1., 2.],
        [6., 8.]])

행렬 곱셈
--------------
Shape of Matrix 1 : torch.Size([2, 2])
Shape of Matrix 1 : torch.Size([2, 1])
mul :  
 tensor([[ 5.],
        [11.]])


###  Mean

In [44]:
t= torch.FloatTensor([1,2])
print('mean :', t.mean())

# longTensor 에 대해서는 mean을 잘 수행하지 못한다.
t = torch.LongTensor([1,2])
try :
    print(t.mean)
except Exception as exc:
    print(exc)
    
    
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.mean())
print(t.mean(dim=0))   # dimension argument - dim 0을 없앤다고 생각하면 됨
print(t.mean(dim=1))
print(t.mean(dim=-1))

mean : tensor(1.5000)
<built-in method mean of Tensor object at 0x00000216EC1A6048>
tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### Sum

In [46]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


###  Max and Argmax
- max : tensor나 행렬에 대해서 가장 큰값을 찾아주는 것
- argmax : 그 인덱스 값을 리턴해주는 것

In [52]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

print(t.max())

print()

# dimension 의 정보도 줄 수 있음
print(t.max(dim=0))  # max 의 값 뿐만 아니라, 인덱스값도 같이 받아줌 
print()
print('MAX : ', t.max(dim=0)[0])
print()
print('Argmax : ', t.max(dim=0)[1])
print()
print(t.max(dim=1))
print()
print(t.max(dim=-1))

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))

MAX :  tensor([3., 4.])

Argmax :  tensor([1, 1])

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
