### PyTorch Basic

 Pytorch 기초 사용법 : 타입만 다를 뿐 numpy와 같게 동작한다.

In [8]:
import numpy as np
import torch

In [9]:
# 타입만 다를 뿐, numpy 와 같게 동작한다.
print(np.arange(9))
print(torch.arange(9))

[0 1 2 3 4 5 6 7 8]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])


In [17]:
# shape 를 알수 있음
nums = torch.arange(6)
nums.shape

torch.Size([6])

In [11]:
type(nums)

torch.Tensor

In [12]:
# 넘파이 변환이 가능함
nums.numpy()

array([0, 1, 2, 3, 4])

In [18]:
# numpy 와 유사하게 reshape 를 할 수 있음
nums.reshape(2,3)

tensor([[0, 1, 2],
        [3, 4, 5]])

In [20]:
# 랜덤으로 3,3 텐서 만들어주기 
randoms = torch.rand((3,3))
randoms

tensor([[0.0872, 0.9097, 0.4892],
        [0.7905, 0.4164, 0.2248],
        [0.4963, 0.1735, 0.3112]])

In [21]:
# np.zeros((3,3)) 와 유사함 
zeros = torch.zeros((3,3))
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [25]:
torch.zeros_like(ones)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [24]:
ones = torch.ones((3,3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [26]:
zeros.size()

torch.Size([3, 3])

### Operations
PyTorch로 수학 연산

In [27]:
# 넘파이처럼 브로드캐스트 가능함
nums * 3 

tensor([ 0,  3,  6,  9, 12, 15])

In [32]:
nums = torch.arange(10)
nums

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
nums = nums.reshape((2,5))
nums + nums 

tensor([[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18]])

In [31]:
torch.add(nums, 3)

tensor([[ 3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12]])

In [33]:
# 넘파이로도 꺼내올 수 있음 
result = torch.add(nums, 3)
result.numpy()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### View
View 보다는, reshape를 더 많이 사용함. 
reshape 과 같은 기능

In [40]:
range_nums = torch.arange(9).reshape(3,3)
range_nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [41]:
range_nums.view(-1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
range_nums.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

### Slice and Index

In [47]:
nums = torch.arange(9).reshape((3,3))
nums

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [48]:
nums[1]

tensor([3, 4, 5])

In [49]:
nums[1,1]

tensor(4)

In [51]:
# 슬라이스로 중간에 있는값을 가져옴
nums[1:, 1:]

tensor([[4, 5],
        [7, 8]])

In [52]:
nums[1:]

tensor([[3, 4, 5],
        [6, 7, 8]])

### Compile
numpy를 torch tensor 로 불러오기

In [55]:
arr = np.array([1,1,1])
arr_torch = torch.from_numpy(arr)
arr_torch  # int 형으로 들어와 있는데 , 이것을 float 형으로 바꿀 수 있음

tensor([1, 1, 1])

In [57]:
# float 로 형변환
arr_torch.float()

tensor([1., 1., 1.])

In [58]:
# device 설정 - cuda(gpu) 가 없다면 자동으로 cpu 로 넘어가게끔 하는 코드
# gpu 인지 신경쓰지말고 그냥 공홈에 나와있는 이 코드를 사용하면 된다고 함. 

device = "cuda" if torch.cuda.is_available() else 'cpu'
device

In [59]:
arr_torch.to(device)  # device로 컴파일 됬다고 생각하면 된다고 함. 

tensor([1, 1, 1])

### AutoGrad
기울기를 주어서 학습이 되도록하는것 

In [62]:
x = torch.ones(2,2, requires_grad = True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [63]:
y = x + 2 
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [64]:
print(y.grad_fn)

In [65]:
z = y* y * 3
out = z.mean()
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [72]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [66]:
out.backward()

In [68]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [70]:
print(x.requires_grad)
print((x ** 2 ).requires_grad)

True
True


In [71]:
# no_grad를 하면 기울기를 구하지 않고, 배치노멀 이런걸 작동이 안됨. 트레인모드보다 빨라짐. 따라서 테스트할 땐 이걸 사용하면 됨 
with torch.no_grad():
    print((x**2).requires_grad) 

False
