## 판다스

- loc : 이름으로 부분집합 조회
- iloc : 번호로 조회
- reset_index : 인덱스 초기화
* df1.merge(df2) : 조인해서 하나의 데이터 프레임으로 만드는것 
* pd.concat([df1,df2],axis=0) :행이름 또는 열이름으로 기준을 연결
    * Nan 값이 들어가게 되면 그 열을 float 타입으로 바꿈
- pivot_table : 롱포멧 데이터를 와이드 포멧으로 바꿈
    * index : 피벗테이블의 인덱스가 되어야 하는 열
    * columns : 이 열의 값이 피벗 테이블의 열 이름으로 만들어짐
    * values : 피벗 테이블의 값으로 들어가 ㄹ열
    * aggfunc : 집계함수
* apply 계열
    * apply : 데이터 프레임, 시리즈, 함수가 뭐냐에 따라 요소별로 적용되거나, 집계됨. 
    * applymap : 데이터프레임에만 사용. 각요소별로 적용
* 결측치 처리
    * dropna, fillna
    * replace : 정규표현식을 이용해 값을 바꿀수있다. 
    * missingno : 패키지를 이용하면 결측치 분포를확인하기쉽다. 
* goupby

## 데이터 시각화
* 데이터 준비하기
* 도화지 크기, 도화지를 나누는 개수
* 그래프 그리기 
    * 단별량 그래프 : 히스토 그램
    * 이변량 그래프 : 산점도 그래프 (scatter, scatterplot),히트맵(상관계수 (corr)를 시각화 
* 그래프 커스터 마이징
    * 축의 눈금과 레이블 
    * 비율을 계산해서 그리는 것을 고려해라

In [1]:
import pandas as pd
import numpy as np

In [2]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]

In [6]:
df = pd.DataFrame(np.c_[l1,l2],columns=["c1","c2"],index=[3,4,5,6])

In [7]:
df.loc[3:4,]

c1  c2
3   1   5
4   2   6

In [8]:
df.iloc[1:3,]

c1  c2
4   2   6
5   3   7

In [9]:
df.reset_index(axis = 1)

TypeError: reset_index() got an unexpected keyword argument 'axis'

In [11]:
df.reset_index (drop = True, inplace=True)

In [12]:
df.loc[:,"c1":"c2"].loc[df.c1%2==0, "c2"]

1    6
3    8
Name: c2, dtype: int32

In [13]:
a = np.arange(24).reshape(3,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [14]:
b = a[:,2:5]
b

array([[ 2,  3,  4],
       [10, 11, 12],
       [18, 19, 20]])

In [15]:
b[:,1]=100

In [16]:
b

array([[  2, 100,   4],
       [ 10, 100,  12],
       [ 18, 100,  20]])

In [17]:
a

array([[  0,   1,   2, 100,   4,   5,   6,   7],
       [  8,   9,  10, 100,  12,  13,  14,  15],
       [ 16,  17,  18, 100,  20,  21,  22,  23]])