### 1. 머신러닝 라이브러리를 이용한 분류

In [11]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [12]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = pd.get_dummies(iris.target).to_numpy()

In [13]:
len(iris_x)

150

In [14]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(iris_x, iris_y,
                                                       test_size= 0.3 , random_state =1)

In [17]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(50,50,30))

In [20]:
mlp.fit(train_x, train_y)

C:\Users\COM\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(50, 50, 30), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [24]:
mlp.score(test_x, test_y)

1.0

### 2.텐선플로우를 이용한 분류

In [2]:
import tensorflow as tf

C:\Users\COM\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\COM\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\COM\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\COM\anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type

In [3]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [4]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = pd.get_dummies(iris.target).to_numpy()

In [40]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(iris_x, iris_y,
                                                       test_size= 0.3 , random_state =1)

In [41]:
print(train_y[0:10])

[[0 0 1]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]
 [0 0 1]]


In [42]:
# 텐서플로우가 2.x 이상이 경우만 1이랑 호환하려고 넣는것

import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [43]:
x = tf.placeholder(tf.float32, [None, 4])
y = tf.placeholder(tf.float32, [None, 3])

In [44]:
# weight와 bias 를 정의해주기 
# variable  : 계속 변경시켜주는 것 

w = tf.Variable(tf.zeros([4,3]))
b = tf.Variable(tf.zeros([3]))


In [45]:
# tf.matmul 행렬의 곱을 나타냄 @ 은 쓸수없음
h = tf.nn.softmax(tf.matmul(x,w)+b)

In [66]:
cross_entropy = -tf.reduce_sum(y * tf.log(h),
                             reduction_indices=[1])

In [67]:
loss = tf.reduce_mean(cross_entropy)

In [68]:
train = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [69]:
# 항상 run 을 해야 결과를 받을 수 있다.
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [70]:
for i in range(100000):
    _, loss_value = sess.run([train,loss], feed_dict= {x:train_x, y:train_y})
    if i  % 10000 == 0:
        print('step %d , %.5f' %( i,loss_value))

step 0 , 1.09861
step 10000 , 0.34161
step 20000 , 0.25734
step 30000 , 0.21406
step 40000 , 0.18753
step 50000 , 0.16957
step 60000 , 0.15658
step 70000 , 0.14673
step 80000 , 0.13899
step 90000 , 0.13274


In [72]:
correct_prediction = tf.equal(tf.argmax(h,1), tf.argmax(y,1)) # 1 은 축을 의미함
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x:test_x,y:test_y}))

0.9777778


In [73]:
print(sess.run(h,feed_dict={x:test_x, y:test_y})[0:10])

[[9.98785913e-01 1.21414929e-03 1.14390726e-10]
 [1.21662915e-01 8.65826964e-01 1.25101535e-02]
 [1.11911949e-02 9.52915430e-01 3.58933881e-02]
 [9.97843266e-01 2.15667766e-03 1.68635106e-09]
 [1.24177197e-04 3.19967508e-01 6.79908276e-01]
 [7.99222011e-03 7.64344692e-01 2.27663085e-01]
 [4.96170891e-04 2.62598515e-01 7.36905217e-01]
 [9.86688435e-01 1.33114867e-02 1.60582701e-07]
 [9.74975944e-01 2.50236727e-02 3.16469425e-07]
 [2.89412856e-05 5.79529479e-02 9.42018092e-01]]


In [74]:
predict_y = sess.run(tf.argmax(h,1), feed_dict={x:test_x})

In [75]:
print(predict_y[0:20])

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0]


In [76]:
print(test_y.argmax(axis=1 )[0:20])

[0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 1 0 0]


In [77]:
cross_tab= pd.crosstab(test_y.argmax(axis=1),predict_y,margins= True)
cross_tab

col_0   0   1   2  All
row_0                 
0      14   0   0   14
1       0  17   1   18
2       0   0  13   13
All    14  17  14   45

### 케라스를 이용한 방법

In [78]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [79]:
iris = datasets.load_iris()
iris_x = iris.data
iris_y = pd.get_dummies(iris.target).to_numpy()

In [80]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(iris_x, iris_y,
                                                       test_size= 0.3 , random_state =1)

In [82]:
train_x.shape, train_y.shape

((105, 4), (105, 3))

In [83]:
from tensorflow.keras.models import Sequential
model = Sequential()

In [86]:
from tensorflow.keras.layers import Input, Dense
model.add(Input(4))
model.add(Dense(50, activation="relu"))
model.add(Dense(50, activation="relu"))
model.add(Dense(30, activation="relu"))
model.add(Dense(3, activation="softmax"))

In [87]:
model.compile(optimizer ="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [88]:
model.fit(train_x, train_y, batch_size=50, epochs=200, verbose=1)

# 1 epoch 당 여러번의 weight 조정이 됨 

Epoch 1/200
105/105 [==============================] - 0s 594us/sample - loss: 1.1151 - acc: 0.3429
Epoch 2/200
105/105 [==============================] - 0s 0s/sample - loss: 1.0256 - acc: 0.5143
Epoch 3/200
105/105 [==============================] - 0s 0s/sample - loss: 0.9561 - acc: 0.6952
Epoch 4/200
105/105 [==============================] - 0s 0s/sample - loss: 0.9340 - acc: 0.6762
Epoch 5/200
105/105 [==============================] - 0s 149us/sample - loss: 0.9080 - acc: 0.6381
Epoch 6/200
105/105 [==============================] - 0s 0s/sample - loss: 0.8678 - acc: 0.6952
Epoch 7/200
105/105 [==============================] - 0s 0s/sample - loss: 0.8227 - acc: 0.6952
Epoch 8/200
105/105 [==============================] - 0s 158us/sample - loss: 0.7739 - acc: 0.6952
Epoch 9/200
105/105 [==============================] - 0s 29us/sample - loss: 0.7223 - acc: 0.6952
Epoch 10/200
105/105 [==============================] - 0s 48us/sample - loss: 0.6824 - acc: 0.6952
Epoch 11/200
105

105/105 [==============================] - 0s 38us/sample - loss: 0.0988 - acc: 0.9619
Epoch 84/200
105/105 [==============================] - 0s 38us/sample - loss: 0.0972 - acc: 0.9714
Epoch 85/200
105/105 [==============================] - 0s 29us/sample - loss: 0.0963 - acc: 0.9619
Epoch 86/200
105/105 [==============================] - 0s 29us/sample - loss: 0.0849 - acc: 0.9619
Epoch 87/200
105/105 [==============================] - 0s 38us/sample - loss: 0.0980 - acc: 0.9714
Epoch 88/200
105/105 [==============================] - 0s 38us/sample - loss: 0.0970 - acc: 0.9714
Epoch 89/200
105/105 [==============================] - 0s 38us/sample - loss: 0.0881 - acc: 0.9714
Epoch 90/200
105/105 [==============================] - 0s 38us/sample - loss: 0.0876 - acc: 0.9714
Epoch 91/200
105/105 [==============================] - 0s 29us/sample - loss: 0.0860 - acc: 0.9714
Epoch 92/200
105/105 [==============================] - 0s 19us/sample - loss: 0.0850 - acc: 0.9714
Epoch 93/200


In [89]:
import numpy as np
pred = np.argmax(model.predict(test_x), axis=1)
pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 2,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1], dtype=int64)

In [90]:
pd.crosstab(np.argmax(test_y, axis =1), pred)

col_0   0   1   2
row_0            
0      14   0   0
1       0  16   2
2       0   0  13

In [91]:
model.evaluate(test_x, test_y)

45/45 [==============================] - 0s 622us/sample - loss: 0.0666 - acc: 0.9556


[0.06659174429045783, 0.95555556]

## 와인데이터 

In [92]:
import numpy as np
import pandas as pd

In [94]:
redwine = pd.read_csv("winequality-red.csv", sep= ";")
redwine_x = redwine.iloc[: , :-1].to_numpy()
redwine_y = pd.get_dummies(redwine.iloc[:,-1].to_numpy())

In [109]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(redwine_x, redwine_y,
                                                       test_size= 0.3 , random_state =1)

In [110]:
train_x.shape, train_y.shape

((1119, 11), (1119, 6))

In [120]:
x = tf.placeholder(tf.float32, [None, 11])
y = tf.placeholder(tf.float32, [None, 6])

In [121]:
w = tf.Variable(tf.zeros([11,6]))
b = tf.Variable(tf.zeros([6]))

In [122]:
h = tf.nn.softmax(tf.matmul(x,w)+b)
cross_entropy = -tf.reduce_sum(y * tf.log(h), reduction_indices=[1])

In [123]:
loss = tf.reduce_mean(cross_entropy)

In [124]:
train = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [125]:
# 항상 run 을 해야 결과를 받을 수 있다.
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [126]:
for i in range(100000):
    _, loss_value = sess.run([train,loss], feed_dict= {x:train_x, y:train_y})
    if i  % 10000 == 0:
        print('step %d , %.5f' %( i,loss_value))

step 0 , 1.79176
step 10000 , 1.08176
step 20000 , 1.05125
step 30000 , 1.03211
step 40000 , 1.01921
step 50000 , 1.01002
step 60000 , 1.00318
step 70000 , 0.99788
step 80000 , 0.99364
step 90000 , 0.99014


In [127]:
correct_prediction = tf.equal(tf.argmax(h,1), tf.argmax(y,1)) # 1 은 축을 의미함
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x:test_x,y:test_y}))

0.57708335


In [128]:
predict_y = sess.run(tf.argmax(h,1), feed_dict={x:test_x})

In [129]:
predict_y = sess.run(tf.argmax(h,1), feed_dict={x:test_x})
cross_tab= pd.crosstab(test_y.argmax(axis=1),predict_y,margins= True)
cross_tab

AttributeError: 'DataFrame' object has no attribute 'argmax'

### 케라스 이용

In [ ]:
import numpy as np
import pandas as pd
from sklearn import datasets

- 무슨 모델을 쓰던, 데이터를 불러오는 것은 다 같음 

In [ ]:
redwine = pd.read_csv("winequality-red.csv", sep= ";")
redwine_x = redwine.iloc[: , :-1].to_numpy()
redwine_y = pd.get_dummies(redwine.iloc[:,-1].to_numpy())
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(redwine_x, redwine_y,
                                                       test_size= 0.3 , random_state =1)
train_x.shape, train_y.shape

In [131]:
from tensorflow.keras.models import Sequential
model = Sequential()
from tensorflow.keras.layers import Input, Dense
model.add(Input(11))
model.add(Dense(50, activation="relu"))
model.add(Dense(50, activation="relu"))
model.add(Dense(30, activation="relu"))
model.add(Dense(6, activation="softmax"))
model.compile(optimizer ="adam", loss="categorical_crossentropy", metrics=["accuracy"]) # 평가항목 
model.fit(train_x, train_y, batch_size=50, epochs=200, verbose=1)
import numpy as np
pred = np.argmax(model.predict(test_x), axis=1)
pd.crosstab(np.argmax(test_y, axis =1), pred)
model.evaluate(test_x, test_y)

Epoch 1/200
1119/1119 [==============================] - 0s 56us/sample - loss: 1.8006 - acc: 0.3878
Epoch 2/200
1119/1119 [==============================] - 0s 28us/sample - loss: 1.2062 - acc: 0.4933
Epoch 3/200
1119/1119 [==============================] - 0s 17us/sample - loss: 1.1609 - acc: 0.5013
Epoch 4/200
1119/1119 [==============================] - 0s 18us/sample - loss: 1.1533 - acc: 0.4790
Epoch 5/200
1119/1119 [==============================] - 0s 17us/sample - loss: 1.1459 - acc: 0.4969
Epoch 6/200
1119/1119 [==============================] - 0s 18us/sample - loss: 1.1383 - acc: 0.4826
Epoch 7/200
1119/1119 [==============================] - 0s 18us/sample - loss: 1.1206 - acc: 0.4978
Epoch 8/200
1119/1119 [==============================] - 0s 17us/sample - loss: 1.1167 - acc: 0.5147
Epoch 9/200
1119/1119 [==============================] - 0s 17us/sample - loss: 1.1311 - acc: 0.4879
Epoch 10/200
1119/1119 [==============================] - 0s 20us/sample - loss: 1.1141 - a

1119/1119 [==============================] - 0s 16us/sample - loss: 0.8797 - acc: 0.6220
Epoch 161/200
1119/1119 [==============================] - 0s 16us/sample - loss: 0.8641 - acc: 0.6318
Epoch 162/200
1119/1119 [==============================] - 0s 16us/sample - loss: 0.8689 - acc: 0.6381
Epoch 163/200
1119/1119 [==============================] - 0s 15us/sample - loss: 0.8578 - acc: 0.6273
Epoch 164/200
1119/1119 [==============================] - 0s 16us/sample - loss: 0.8608 - acc: 0.6399
Epoch 165/200
1119/1119 [==============================] - 0s 16us/sample - loss: 0.8501 - acc: 0.6336
Epoch 166/200
1119/1119 [==============================] - 0s 15us/sample - loss: 0.8545 - acc: 0.6425
Epoch 167/200
1119/1119 [==============================] - 0s 15us/sample - loss: 0.8606 - acc: 0.6443
Epoch 168/200
1119/1119 [==============================] - 0s 15us/sample - loss: 0.8554 - acc: 0.6515
Epoch 169/200
1119/1119 [==============================] - 0s 15us/sample - loss: 0.894

ValueError: Shape of passed values is (480, 1), indices imply (480, 6)

## 필기체 숫자이미지 분류 (mnist) 

In [133]:
import cv2
import numpy as np

img = cv2.imread("digits.png", cv2.IMREAD_GRAYSCALE)
print(img.shape)

(1000, 2000)


In [134]:
cv2.imshow("number", img)
cv2.waitKey(0)


-1

### 텐서플로우를 이용한 분류

In [159]:
import tensorflow as tf
import numpy as np
import pandas as pd

img = cv2.imread("digits.png", cv2.IMREAD_GRAYSCALE)
print(img.shape)

(1000, 2000)


In [160]:
cells = [np.hsplit(row , 100) for row in np.vsplit(img,50)]
x = np.array(cells)
X = x[:,:].reshape(-1,400).astype(np.float32)
y= pd.get_dummies(np.repeat(np.arange(10),500)).to_numpy()

In [161]:
from sklearn.model_selection import train_test_split
train_x , test_x , train_y, test_y = train_test_split(X, y,test_size= 0.3)

In [162]:
x = tf.placeholder(tf.float32, [None, 400])
y = tf.placeholder(tf.float32, [None, 10])

In [163]:
w1 = tf.Variable(tf.zeros([400,512]))  # 어제는 0으로 웨이트를 초기화해줌 
b1 = tf.Variable(tf.zeros([512]))
h1 = tf.nn.relu(tf.matmul(x,w1)+b1)

In [164]:
w2 = tf.Variable(tf.zeros([512,256]))
b2 = tf.Variable(tf.zeros([256]))
h2 = tf.nn.relu(tf.matmul(h1,w2)+b2)

In [165]:
w3 = tf.Variable(tf.zeros([256,128]))
b3 = tf.Variable(tf.zeros([128]))
h3 = tf.nn.relu(tf.matmul(h2,w3)+b3)

In [166]:
w = tf.Variable(tf.zeros([128,10]))
b = tf.Variable(tf.zeros([10]))

In [167]:
h = tf.nn.softmax(tf.matmul(h3,w)+b)

In [168]:
cross_entropy =-tf.reduce_sum(y*tf.log(h), reduction_indices=[1])

In [169]:
loss = tf.reduce_mean(cross_entropy)  # 손실 함수 

In [170]:
train = tf.train.GradientDescentOptimizer(0.001).minimize(loss)

In [171]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [172]:
for i in range(30001):
    _, loss_value = sess.run([train, loss], feed_dict={x:train_x, y:train_y})
    if i % 10000 ==0 :
        print("step %d, %.5f" %(i, loss_value))


step 0, 2.30260
step 10000, 2.30233
step 20000, 2.30227
step 30000, 2.30228


In [179]:
correct_prediction = tf.equal(tf.argmax(h,1), tf.argmax(y,1)) # 1 은 축을 의미함
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
print(sess.run(accuracy, feed_dict={x:test_x,y:test_y}))

0.08533333


In [180]:
predict_y = sess.run(tf.argmax(h,1), feed_dict={x:test_x})
cross_tab= pd.crosstab(test_y.argmax(axis=1),predict_y,margins= True)
cross_tab

col_0     1   All
row_0            
0       149   149
1       128   128
2       155   155
3       160   160
4       156   156
5       148   148
6       144   144
7       158   158
8       149   149
9       153   153
All    1500  1500

## 케라스

In [178]:
tot_cnt = len(train_x)

for epoch in range(1000):
    avg_loss = 0
    batch_size = 128
    tot_iter = int(tot_cnt / batch_size)
    for step in range(tot_iter):
        batch_X = train_x[int(step*batch_size):int((step+1)*batch_size)]
        batch_y = train_y[int(step*batch_size):int((step+1)*batch_size)]
        _, loss_ = sess.run([train, loss], feed_dict={x:batch_X, y:batch_y})
        avg_loss += (loss_ / tot_iter)
        print("{:03d} - {:f}".format(step, loss_), end="\r")
    if len(train_x)//tot_iter != 0:
        batch_X = train_x[int(tot_iter*batch_size):]
        batch_y = train_y[int(tot_iter*batch_size):]
        _, loss_ = sess.run([train, loss], feed_dict={x:batch_X, y:batch_y})
        avg_loss += (loss_ / tot_iter)
        print("{:03d} - {:f}".format(step, loss_), end="\r")
    if epoch%100 ==0:
        print("step {}, train loss {}".format(epoch, avg_loss))



step 999, train loss 2.387463640283655


In [181]:
predict_y = sess.run(tf.argmax(h,1), feed_dict={x:test_x})
cross_tab= pd.crosstab(test_y.argmax(axis=1),predict_y,margins= True)
cross_tab

col_0     1   All
row_0            
0       149   149
1       128   128
2       155   155
3       160   160
4       156   156
5       148   148
6       144   144
7       158   158
8       149   149
9       153   153
All    1500  1500